const CRYPTOS = {
  // 常用幣種
  BTC: { type: "crypto" as const, code: "BTC", name: "Bitcoin" },
  ETH: { type: "crypto" as const, code: "ETH", name: "Ethereum" },
  USDT: { type: "crypto" as const, code: "USDT", name: "Tether" },
  USDC: { type: "crypto" as const, code: "USDC", name: "USD Coin" },
  XRP: { type: "crypto" as const, code: "XRP", name: "XRP" },
  ADA: { type: "crypto" as const, code: "ADA", name: "Cardano" },

  // 一般幣種，依字母排序
  "1INCH": { type: "crypto" as const, code: "1INCH", name: "1inch Network" },
  A8: { type: "crypto" as const, code: "A8", name: "Ancient8" },
  AAVE: { type: "crypto" as const, code: "AAVE", name: "Aave" },
  ABT: { type: "crypto" as const, code: "ABT", name: "Arcblock" },
  ACH: { type: "crypto" as const, code: "ACH", name: "Alchemy Pay" },
  ACS: { type: "crypto" as const, code: "ACS", name: "Access" },
  ACX: { type: "crypto" as const, code: "ACX", name: "Across Protocol" },

  AERGO: { type: "crypto" as const, code: "AERGO", name: "Aergo" },
  AERO: { type: "crypto" as const, code: "AERO", name: "Aerodrome Finance" },
  AGLD: { type: "crypto" as const, code: "AGLD", name: "Adventure Gold" },
  AIOZ: { type: "crypto" as const, code: "AIOZ", name: "AIOZ Network" },
  AKT: { type: "crypto" as const, code: "AKT", name: "Akash Network" },
  ALCX: { type: "crypto" as const, code: "ALCX", name: "Alchemix" },
  ALEO: { type: "crypto" as const, code: "ALEO", name: "Aleo" },
  ALEPH: { type: "crypto" as const, code: "ALEPH", name: "Aleph.im" },
  ALGO: { type: "crypto" as const, code: "ALGO", name: "Algorand" },
  ALICE: { type: "crypto" as const, code: "ALICE", name: "MyNeighborAlice" },
  ALT: { type: "crypto" as const, code: "ALT", name: "Altlayer" },
  AMP: { type: "crypto" as const, code: "AMP", name: "Amp" },
  ANKR: { type: "crypto" as const, code: "ANKR", name: "Ankr" },
  ANT: { type: "crypto" as const, code: "ANT", name: "Aragon" },
  APE: { type: "crypto" as const, code: "APE", name: "ApeCoin" },
  API3: { type: "crypto" as const, code: "API3", name: "Api3" },
  APT: { type: "crypto" as const, code: "APT", name: "Aptos" },
  ARB: { type: "crypto" as const, code: "ARB", name: "Arbitrum" },
  ARKM: { type: "crypto" as const, code: "ARKM", name: "Arkham" },
  ARPA: { type: "crypto" as const, code: "ARPA", name: "ARPA Chain" },
  ASM: { type: "crypto" as const, code: "ASM", name: "Assemble Protocol" },
  AST: { type: "crypto" as const, code: "AST", name: "AirSwap" },
  ATA: { type: "crypto" as const, code: "ATA", name: "Automata" },
  ATH: {
    type: "crypto" as const,
    code: "ATH",
    name: "Athens (ATH?)" /* not confirmed */,
  },
  ATOM: {
    type: "crypto" as const,
    code: "ATOM",
    name: "Cosmos" /* ATOM is Cosmos */,
  },
  AUCTION: {
    type: "crypto" as const,
    code: "AUCTION",
    name: "Auction" /* exact name may vary */,
  },
  AUDIO: { type: "crypto" as const, code: "AUDIO", name: "Audius" },
  AURORA: { type: "crypto" as const, code: "AURORA", name: "Aurora" },
  AVAX: { type: "crypto" as const, code: "AVAX", name: "Avalanche" },
  AVT: {
    type: "crypto" as const,
    code: "AVT",
    name: "ArtVerse Token" /* or AVT — check source */,
  },
  AXL: { type: "crypto" as const, code: "AXL", name: "Axelar" },
  AXS: { type: "crypto" as const, code: "AXS", name: "Axie Infinity" },
  B3: {
    type: "crypto" as const,
    code: "B3",
    name: "B3 Coin", // lesser-known; project name used
  },
  BADGER: { type: "crypto" as const, code: "BADGER", name: "Badger DAO" },
  BAL: { type: "crypto" as const, code: "BAL", name: "Balancer" },
  BAND: { type: "crypto" as const, code: "BAND", name: "Band Protocol" },
  BAT: { type: "crypto" as const, code: "BAT", name: "Basic Attention Token" },
  BCH: { type: "crypto" as const, code: "BCH", name: "Bitcoin Cash" },
  BERA: {
    type: "crypto" as const,
    code: "BERA",
    name: "Berachain (BERA)", // chain native token
  },
  BICO: { type: "crypto" as const, code: "BICO", name: "Biconomy" },
  BIGTIME: { type: "crypto" as const, code: "BIGTIME", name: "Big Time" },
  BIT: { type: "crypto" as const, code: "BIT", name: "BitDAO" },
  BLAST: {
    type: "crypto" as const,
    code: "BLAST",
    name: "Blast.io", // ecosystem token; most common name
  },
  BLUR: { type: "crypto" as const, code: "BLUR", name: "Blur" },
  BLZ: { type: "crypto" as const, code: "BLZ", name: "Bluzelle" },
  BNT: { type: "crypto" as const, code: "BNT", name: "Bancor" },
  BOBA: { type: "crypto" as const, code: "BOBA", name: "Boba Network" },
  BOND: { type: "crypto" as const, code: "BOND", name: "BarnBridge" },
  BONK: { type: "crypto" as const, code: "BONK", name: "Bonk" },

  BTRST: { type: "crypto" as const, code: "BTRST", name: "Braintrust" },
  BUSD: { type: "crypto" as const, code: "BUSD", name: "Binance USD" },
  C98: { type: "crypto" as const, code: "C98", name: "Coin98" },
  CBETH: {
    type: "crypto" as const,
    code: "CBETH",
    name: "Coinbase Wrapped Staked ETH",
  },
  CELR: { type: "crypto" as const, code: "CELR", name: "Celer Network" },
  CGLD: { type: "crypto" as const, code: "CGLD", name: "Celo" },
  CHZ: { type: "crypto" as const, code: "CHZ", name: "Chiliz" },
  CLANKER: { type: "crypto" as const, code: "CLANKER", name: "Clanker" }, // rare/less-known — verify yourself
  CLV: { type: "crypto" as const, code: "CLV", name: "Clover" },
  COMP: { type: "crypto" as const, code: "COMP", name: "Compound" },
  COOKIE: { type: "crypto" as const, code: "COOKIE", name: "Cookie DAO" }, // or "Cookie" token — may vary
  CORECHAIN: { type: "crypto" as const, code: "CORECHAIN", name: "CoreChain" }, // less common token — verify
  COTI: { type: "crypto" as const, code: "COTI", name: "COTI" },
  COVAL: {
    type: "crypto" as const,
    code: "COVAL",
    name: "Covalent Query Token",
  },
  COW: { type: "crypto" as const, code: "COW", name: "CoW Protocol" },
  CRO: { type: "crypto" as const, code: "CRO", name: "Cronos" },
  CRPT: { type: "crypto" as const, code: "CRPT", name: "Cryptex" },
  CRV: { type: "crypto" as const, code: "CRV", name: "Curve DAO Token" },
  CTSI: { type: "crypto" as const, code: "CTSI", name: "Cartesi" },
  CTX: { type: "crypto" as const, code: "CTX", name: "Cryptex (CTX)" },
  CVC: { type: "crypto" as const, code: "CVC", name: "Civic" },
  CVX: { type: "crypto" as const, code: "CVX", name: "Convex Finance" },
  DAI: { type: "crypto" as const, code: "DAI", name: "Dai" },
  DAR: { type: "crypto" as const, code: "DAR", name: "Mines of Dalarnia" },
  DASH: { type: "crypto" as const, code: "DASH", name: "Dash" },
  DDX: { type: "crypto" as const, code: "DDX", name: "DerivaDAO" },
  DEGEN: { type: "crypto" as const, code: "DEGEN", name: "Degen" }, // multiple chains use DEGEN, but common name is "Degen"
  DESO: { type: "crypto" as const, code: "DESO", name: "Decentralized Social" },
  DEXT: { type: "crypto" as const, code: "DEXT", name: "DexTools" },
  DIA: { type: "crypto" as const, code: "DIA", name: "DIA" },
  DIMO: { type: "crypto" as const, code: "DIMO", name: "DIMO" },
  DNT: { type: "crypto" as const, code: "DNT", name: "District0x" },
  DOGE: { type: "crypto" as const, code: "DOGE", name: "Dogecoin" },
  DOGINME: { type: "crypto" as const, code: "DOGINME", name: "Dog In Me" }, // meme token, name consistent across listings
  DOT: { type: "crypto" as const, code: "DOT", name: "Polkadot" },
  DREP: { type: "crypto" as const, code: "DREP", name: "Drep" },
  DRIFT: { type: "crypto" as const, code: "DRIFT", name: "Drift Token" }, // used by Drift Protocol; naming varies but this is most common
  DYP: { type: "crypto" as const, code: "DYP", name: "DeFi Yield Protocol" },
  EDGE: { type: "crypto" as const, code: "EDGE", name: "Edge" }, // several small-cap tokens use EDGE; "Edge" is the canonical name
  EGLD: { type: "crypto" as const, code: "EGLD", name: "MultiversX" }, // formerly Elrond
  EIGEN: { type: "crypto" as const, code: "EIGEN", name: "Eigen" }, // EigenLayer restaking token
  ELA: { type: "crypto" as const, code: "ELA", name: "Elastos" },
  ENJ: { type: "crypto" as const, code: "ENJ", name: "Enjin Coin" },
  ENS: { type: "crypto" as const, code: "ENS", name: "Ethereum Name Service" },
  EOS: { type: "crypto" as const, code: "EOS", name: "EOS" },
  ERN: { type: "crypto" as const, code: "ERN", name: "Ethernity Chain" },
  ETC: { type: "crypto" as const, code: "ETC", name: "Ethereum Classic" },

  ETHFI: { type: "crypto" as const, code: "ETHFI", name: "ether.fi" },
  EURC: { type: "crypto" as const, code: "EURC", name: "Euro Coin" }, // Circle EUR stablecoin
  FAI: { type: "crypto" as const, code: "FAI", name: "FairAI" }, // multiple FAIs exist; FairAI is the widely recognized one
  FARM: { type: "crypto" as const, code: "FARM", name: "Harvest Finance" },
  FET: { type: "crypto" as const, code: "FET", name: "Fetch.ai" },
  FIDA: { type: "crypto" as const, code: "FIDA", name: "Bonfida" },
  FIL: { type: "crypto" as const, code: "FIL", name: "Filecoin" },
  FIS: { type: "crypto" as const, code: "FIS", name: "StaFi" },
  FLOKI: { type: "crypto" as const, code: "FLOKI", name: "Floki" },
  FLOW: { type: "crypto" as const, code: "FLOW", name: "Flow" },
  FLR: { type: "crypto" as const, code: "FLR", name: "Flare" },
  FORT: { type: "crypto" as const, code: "FORT", name: "Forta" },
  FORTH: {
    type: "crypto" as const,
    code: "FORTH",
    name: "Ampleforth Governance Token",
  },
  FOX: { type: "crypto" as const, code: "FOX", name: "ShapeShift FOX Token" },
  FX: { type: "crypto" as const, code: "FX", name: "Function X" },
  G: {
    type: "crypto" as const,
    code: "G",
    name: "Gravity", // The most recognized token using symbol G
  },
  GAL: { type: "crypto" as const, code: "GAL", name: "Project Galxe" },
  GALA: { type: "crypto" as const, code: "GALA", name: "Gala" },
  GFI: { type: "crypto" as const, code: "GFI", name: "Goldfinch" },
  GHST: { type: "crypto" as const, code: "GHST", name: "Aavegotchi" },
  GIGA: {
    type: "crypto" as const,
    code: "GIGA",
    name: "Gigaverse", // multiple GIGA tokens exist; this is the primary one
  },
  GLM: { type: "crypto" as const, code: "GLM", name: "Golem" },
  GMT: { type: "crypto" as const, code: "GMT", name: "STEPN" },
  GNO: { type: "crypto" as const, code: "GNO", name: "Gnosis" },
  GNT: {
    type: "crypto" as const,
    code: "GNT",
    name: "Golem (Legacy)", // replaced by GLM
  },
  GODS: { type: "crypto" as const, code: "GODS", name: "Gods Unchained" },
  GRT: { type: "crypto" as const, code: "GRT", name: "The Graph" },
  GST: { type: "crypto" as const, code: "GST", name: "Green Satoshi Token" },
  GTC: { type: "crypto" as const, code: "GTC", name: "Gitcoin" },
  GUSD: { type: "crypto" as const, code: "GUSD", name: "Gemini Dollar" },
  GYEN: {
    type: "crypto" as const,
    code: "GYEN",
    name: "GYEN (GMO Japanese Yen Stablecoin)",
  },
  HBAR: { type: "crypto" as const, code: "HBAR", name: "Hedera" },
  HFT: { type: "crypto" as const, code: "HFT", name: "Hashflow" },
  HIGH: { type: "crypto" as const, code: "HIGH", name: "Highstreet" },
  HNT: { type: "crypto" as const, code: "HNT", name: "Helium" },
  HONEY: {
    type: "crypto" as const,
    code: "HONEY",
    name: "Honey Token", // used by several ecosystems; main one is Honey Finance
  },
  HOPR: { type: "crypto" as const, code: "HOPR", name: "HOPR" },
  ICP: { type: "crypto" as const, code: "ICP", name: "Internet Computer" },
  IDEX: { type: "crypto" as const, code: "IDEX", name: "IDEX" },
  ILV: { type: "crypto" as const, code: "ILV", name: "Illuvium" },
  IMX: { type: "crypto" as const, code: "IMX", name: "Immutable" },
  INDEX: { type: "crypto" as const, code: "INDEX", name: "Index Coop" },
  INJ: { type: "crypto" as const, code: "INJ", name: "Injective" },
  INV: { type: "crypto" as const, code: "INV", name: "Inverse Finance" },
  IO: { type: "crypto" as const, code: "IO", name: "io.net" },
  IOTX: { type: "crypto" as const, code: "IOTX", name: "IoTeX" },
  IP: {
    type: "crypto" as const,
    code: "IP",
    name: "Particle Network (IP Token)", // Only major token with symbol IP
  },
  JASMY: { type: "crypto" as const, code: "JASMY", name: "JasmyCoin" },
  JTO: { type: "crypto" as const, code: "JTO", name: "Jito" },
  JUP: { type: "crypto" as const, code: "JUP", name: "Jupiter" },
  KAITO: { type: "crypto" as const, code: "KAITO", name: "Kaito AI" },
  KARRAT: {
    type: "crypto" as const,
    code: "KARRAT",
    name: "KARRAT", // Gaming ecosystem token
  },
  KAVA: { type: "crypto" as const, code: "KAVA", name: "Kava" },
  KEEP: { type: "crypto" as const, code: "KEEP", name: "Keep Network" },
  KERNEL: {
    type: "crypto" as const,
    code: "KERNEL",
    name: "Kernel", // small-cap token, listed on niche markets
  },
  KEYCAT: {
    type: "crypto" as const,
    code: "KEYCAT",
    name: "Keycat", // meme-token ecosystem
  },
  KNC: { type: "crypto" as const, code: "KNC", name: "Kyber Network Crystal" },
  KRL: { type: "crypto" as const, code: "KRL", name: "Kryll" },
  KSM: { type: "crypto" as const, code: "KSM", name: "Kusama" },
  L3: {
    type: "crypto" as const,
    code: "L3",
    name: "Layer3", // L3 token
  },
  LCX: { type: "crypto" as const, code: "LCX", name: "LCX" },
  LDO: { type: "crypto" as const, code: "LDO", name: "Lido DAO" },
  LINK: { type: "crypto" as const, code: "LINK", name: "Chainlink" },
  LIT: { type: "crypto" as const, code: "LIT", name: "Litentry" },
  LOKA: {
    type: "crypto" as const,
    code: "LOKA",
    name: "League of Kingdoms Arena",
  },
  LOOM: { type: "crypto" as const, code: "LOOM", name: "Loom Network" },
  LPT: { type: "crypto" as const, code: "LPT", name: "Livepeer" },
  LQTY: { type: "crypto" as const, code: "LQTY", name: "Liquity" },
  LRC: { type: "crypto" as const, code: "LRC", name: "Loopring" },
  LRDS: {
    type: "crypto" as const,
    code: "LRDS",
    name: "Lords", // token for crypto game ecosystem
  },
  LSETH: {
    type: "crypto" as const,
    code: "LSETH",
    name: "Liquid Staked ETH", // similar to swETH, cbETH—generic staked ETH wrapper token
  },
  LTC: { type: "crypto" as const, code: "LTC", name: "Litecoin" },
  MAGIC: {
    type: "crypto" as const,
    code: "MAGIC",
    name: "MAGIC (Treasure DAO)",
  },
  MANA: { type: "crypto" as const, code: "MANA", name: "Decentraland" },
  MANTLE: { type: "crypto" as const, code: "MANTLE", name: "Mantle" },
  MASK: { type: "crypto" as const, code: "MASK", name: "Mask Network" },
  MATH: { type: "crypto" as const, code: "MATH", name: "MATH" },
  MATIC: { type: "crypto" as const, code: "MATIC", name: "Polygon" },
  MCO2: { type: "crypto" as const, code: "MCO2", name: "Moss Carbon Credit" },
  MDT: { type: "crypto" as const, code: "MDT", name: "Measurable Data Token" },
  ME: { type: "crypto" as const, code: "ME", name: "Magic Eden Token" },
  MEDIA: { type: "crypto" as const, code: "MEDIA", name: "Media Network" },
  METIS: { type: "crypto" as const, code: "METIS", name: "Metis" },
  MINA: { type: "crypto" as const, code: "MINA", name: "Mina Protocol" },
  MIR: { type: "crypto" as const, code: "MIR", name: "Mirror Protocol" },
  MKR: { type: "crypto" as const, code: "MKR", name: "Maker" },
  MLN: {
    type: "crypto" as const,
    code: "MLN",
    name: "Enzyme (formerly Melon)",
  },
  MNDE: { type: "crypto" as const, code: "MNDE", name: "Marinade" },
  MOBILE: { type: "crypto" as const, code: "MOBILE", name: "Helium Mobile" },
  MOG: { type: "crypto" as const, code: "MOG", name: "Mog Coin" },
  MONA: { type: "crypto" as const, code: "MONA", name: "Monavale" },
  MOODENG: {
    type: "crypto" as const,
    code: "MOODENG",
    name: "Moo Deng", // meme token
  },
  MORPHO: { type: "crypto" as const, code: "MORPHO", name: "Morpho" },
  MOVE: {
    type: "crypto" as const,
    code: "MOVE",
    name: "Move Token", // used by on-chain social projects
  },
  MPL: { type: "crypto" as const, code: "MPL", name: "Maple" },
  MSOL: { type: "crypto" as const, code: "MSOL", name: "Marinade Staked SOL" },
  MTL: { type: "crypto" as const, code: "MTL", name: "Metal DAO" },
  MULTI: { type: "crypto" as const, code: "MULTI", name: "Multichain" },
  MUSD: { type: "crypto" as const, code: "MUSD", name: "mStable USD" },
  MUSE: { type: "crypto" as const, code: "MUSE", name: "Muse (NFT20)" },
  MXC: { type: "crypto" as const, code: "MXC", name: "MXC" },
  NCT: { type: "crypto" as const, code: "NCT", name: "NFTCraft" },
  NEAR: { type: "crypto" as const, code: "NEAR", name: "NEAR Protocol" },
  NEON: { type: "crypto" as const, code: "NEON", name: "Neon EVM" },
  NEST: { type: "crypto" as const, code: "NEST", name: "Nest Protocol" },
  NKN: { type: "crypto" as const, code: "NKN", name: "NKN" },
  NMR: { type: "crypto" as const, code: "NMR", name: "Numeraire" },
  NU: { type: "crypto" as const, code: "NU", name: "NuCypher" },
  OCEAN: { type: "crypto" as const, code: "OCEAN", name: "Ocean Protocol" },
  OGN: { type: "crypto" as const, code: "OGN", name: "Origin Protocol" },
  OMG: { type: "crypto" as const, code: "OMG", name: "OMG Network" },
  OMNI: {
    type: "crypto" as const,
    code: "OMNI",
    name: "Omni", // less common token, confirm project
  },
  ONDO: { type: "crypto" as const, code: "ONDO", name: "Ondo" },
  OOKI: { type: "crypto" as const, code: "OOKI", name: "Ooki DAO" },
  OP: { type: "crypto" as const, code: "OP", name: "Optimism" },
  ORCA: { type: "crypto" as const, code: "ORCA", name: "Orca" },
  ORN: { type: "crypto" as const, code: "ORN", name: "Orion Protocol" },
  OSMO: { type: "crypto" as const, code: "OSMO", name: "Osmosis" },
  OXT: { type: "crypto" as const, code: "OXT", name: "Orchid" },
  PAX: { type: "crypto" as const, code: "PAX", name: "Paxos Standard" },
  PAXG: { type: "crypto" as const, code: "PAXG", name: "PAX Gold" },
  PENDLE: { type: "crypto" as const, code: "PENDLE", name: "Pendle" },
  PENGU: { type: "crypto" as const, code: "PENGU", name: "Penguin Finance" },
  PEPE: { type: "crypto" as const, code: "PEPE", name: "Pepe" },
  PERP: { type: "crypto" as const, code: "PERP", name: "Perpetual Protocol" },
  PIRATE: {
    type: "crypto" as const,
    code: "PIRATE",
    name: "Pirate", // meme / niche token — verify
  },
  PLA: { type: "crypto" as const, code: "PLA", name: "PlayDapp" },
  PLU: { type: "crypto" as const, code: "PLU", name: "Pluton" },
  PNG: { type: "crypto" as const, code: "PNG", name: "Pangolin" },
  PNUT: {
    type: "crypto" as const,
    code: "PNUT",
    name: "PNetwork", // verify — some sources vary
  },
  POL: { type: "crypto" as const, code: "POL", name: "Polymesh" },
  POLS: { type: "crypto" as const, code: "POLS", name: "Polkastarter" },
  POLY: { type: "crypto" as const, code: "POLY", name: "Polymath" },
  POND: { type: "crypto" as const, code: "POND", name: "Marlin" },
  POPCAT: {
    type: "crypto" as const,
    code: "POPCAT",
    name: "Popcat Token", // meme token — verify
  },
  POWR: { type: "crypto" as const, code: "POWR", name: "Power Ledger" },
  PRCL: {
    type: "crypto" as const,
    code: "PRCL",
    name: "PRCL", // token unconfirmed; please verify
  },
  PRIME: {
    type: "crypto" as const,
    code: "PRIME",
    name: "Prime", // generic name; check contract / chain for clarity
  },
  PRO: {
    type: "crypto" as const,
    code: "PRO",
    name: "PRO", // ambiguous symbol; verify for correct token
  },
  PROMPT: {
    type: "crypto" as const,
    code: "PROMPT",
    name: "PROMPT", // likely niche token — verify
  },
  PRQ: { type: "crypto" as const, code: "PRQ", name: "PARSIQ" },
  PUNDIX: { type: "crypto" as const, code: "PUNDIX", name: "Pundi X Token" },
  PYR: { type: "crypto" as const, code: "PYR", name: "Rari Governance Token" },
  PYTH: { type: "crypto" as const, code: "PYTH", name: "Pyth Network" },
  PYUSD: { type: "crypto" as const, code: "PYUSD", name: "Pyth USD" },
  QQI: { type: "crypto" as const, code: "QI", name: "BENQI" },
  QNT: { type: "crypto" as const, code: "QNT", name: "Quant" },
  QSP: { type: "crypto" as const, code: "QSP", name: "Quantstamp" },
  QUICK: { type: "crypto" as const, code: "QUICK", name: "Quickswap" },
  RAD: { type: "crypto" as const, code: "RAD", name: "Radicle" },
  RAI: { type: "crypto" as const, code: "RAI", name: "RAI Reflex Index" },
  RARE: { type: "crypto" as const, code: "RARE", name: "SuperRare" },
  RARI: { type: "crypto" as const, code: "RARI", name: "Rarible" },
  RBN: { type: "crypto" as const, code: "RBN", name: "Ribbon Finance" },
  RED: {
    type: "crypto" as const,
    code: "RED",
    name: "Red Token", // multiple tokens use RED; confirm if needed
  },
  REN: { type: "crypto" as const, code: "REN", name: "Ren" },
  RENDER: { type: "crypto" as const, code: "RENDER", name: "Render" },
  REP: { type: "crypto" as const, code: "REP", name: "Augur" },
  REQ: { type: "crypto" as const, code: "REQ", name: "Request" },
  REZ: {
    type: "crypto" as const,
    code: "REZ",
    name: "Renzo", // REZ = Renzo Restaked ETH (liquid restaking)
  },
  RGT: { type: "crypto" as const, code: "RGT", name: "Rari Governance Token" },
  RLC: { type: "crypto" as const, code: "RLC", name: "iExec RLC" },
  RLY: { type: "crypto" as const, code: "RLY", name: "Rally" },
  RNDR: { type: "crypto" as const, code: "RNDR", name: "Render" },
  RONIN: { type: "crypto" as const, code: "RONIN", name: "Ronin" },
  ROSE: { type: "crypto" as const, code: "ROSE", name: "Oasis Network" },
  RPL: { type: "crypto" as const, code: "RPL", name: "Rocket Pool" },
  RSR: { type: "crypto" as const, code: "RSR", name: "Reserve Rights" },
  SAFE: { type: "crypto" as const, code: "SAFE", name: "Safe" },
  SAND: { type: "crypto" as const, code: "SAND", name: "The Sandbox" },
  SD: { type: "crypto" as const, code: "SD", name: "Stader" },
  SEAM: { type: "crypto" as const, code: "SEAM", name: "Seamless Protocol" },
  SEI: { type: "crypto" as const, code: "SEI", name: "Sei" },
  SHDW: { type: "crypto" as const, code: "SHDW", name: "Shadow Token" },
  SHIB: { type: "crypto" as const, code: "SHIB", name: "Shiba Inu" },
  SHPING: { type: "crypto" as const, code: "SHPING", name: "SHPING" },
  SKL: { type: "crypto" as const, code: "SKL", name: "SKALE" },
  SNT: { type: "crypto" as const, code: "SNT", name: "Status" },
  SNX: { type: "crypto" as const, code: "SNX", name: "Synthetix" },
  SOL: { type: "crypto" as const, code: "SOL", name: "Solana" },
  SPA: { type: "crypto" as const, code: "SPA", name: "Sperax" },
  SPELL: { type: "crypto" as const, code: "SPELL", name: "Spell Token" },
  STG: { type: "crypto" as const, code: "STG", name: "Stargate Finance" },
  STORJ: { type: "crypto" as const, code: "STORJ", name: "Storj" },
  STRK: { type: "crypto" as const, code: "STRK", name: "Starknet" },
  STX: { type: "crypto" as const, code: "STX", name: "Stacks" },
  SUI: { type: "crypto" as const, code: "SUI", name: "Sui" },
  SUKU: { type: "crypto" as const, code: "SUKU", name: "SUKU" },
  SUPER: { type: "crypto" as const, code: "SUPER", name: "SuperVerse" },
  SUSHI: { type: "crypto" as const, code: "SUSHI", name: "SushiSwap" },
  SWELL: { type: "crypto" as const, code: "SWELL", name: "Swell Network" },
  SWFTC: { type: "crypto" as const, code: "SWFTC", name: "SwftCoin" },
  SXT: { type: "crypto" as const, code: "SXT", name: "SportsX" },
  SYLO: { type: "crypto" as const, code: "SYLO", name: "Sylo" },
  SYN: { type: "crypto" as const, code: "SYN", name: "Synapse" },
  SYRUP: { type: "crypto" as const, code: "SYRUP", name: "Syrup" },
  T: { type: "crypto" as const, code: "T", name: "Threshold" },
  TAO: { type: "crypto" as const, code: "TAO", name: "Bittensor" },
  TIA: { type: "crypto" as const, code: "TIA", name: "Celestia" },
  TIME: { type: "crypto" as const, code: "TIME", name: "Chrono.tech" },
  TNSR: { type: "crypto" as const, code: "TNSR", name: "Tensor" },
  TONE: { type: "crypto" as const, code: "TONE", name: "TE-FOOD (TONE)" },
  TOSHI: { type: "crypto" as const, code: "TOSHI", name: "Toshi" },
  TRAC: { type: "crypto" as const, code: "TRAC", name: "OriginTrail" },
  TRB: { type: "crypto" as const, code: "TRB", name: "Tellor" },
  TRIBE: { type: "crypto" as const, code: "TRIBE", name: "Tribe" },
  TRU: { type: "crypto" as const, code: "TRU", name: "TrueFi" },
  TRUMP: { type: "crypto" as const, code: "TRUMP", name: "MAGA (TRUMP)" },
  TURBO: { type: "crypto" as const, code: "TURBO", name: "Turbo" },
  TVK: { type: "crypto" as const, code: "TVK", name: "Terra Virtua Kolect" },
  UMA: { type: "crypto" as const, code: "UMA", name: "UMA" },
  UNFI: { type: "crypto" as const, code: "UNFI", name: "Unifi Protocol DAO" },
  UNI: { type: "crypto" as const, code: "UNI", name: "Uniswap" },
  UPI: { type: "crypto" as const, code: "UPI", name: "Pawtocol" },

  UST: { type: "crypto" as const, code: "UST", name: "TerraUSD (Legacy)" },
  VARA: { type: "crypto" as const, code: "VARA", name: "Vara Network" },
  VELO: { type: "crypto" as const, code: "VELO", name: "Velo" },
  VET: { type: "crypto" as const, code: "VET", name: "VeChain" },
  VGX: { type: "crypto" as const, code: "VGX", name: "Voyager Token" },
  VOXEL: { type: "crypto" as const, code: "VOXEL", name: "Voxies" },
  VTHO: { type: "crypto" as const, code: "VTHO", name: "VeThor Token" },
  VVV: { type: "crypto" as const, code: "VVV", name: "Poison Finance (VVV)" },
  WAMPL: { type: "crypto" as const, code: "WAMPL", name: "Wrapped Ampleforth" },
  WAXL: {
    type: "crypto" as const,
    code: "WAXL",
    name: "Axelar Wrapped (WAXL)",
  },
  WBTC: { type: "crypto" as const, code: "WBTC", name: "Wrapped Bitcoin" },
  WCFG: { type: "crypto" as const, code: "WCFG", name: "Wrapped Centrifuge" },
  WELL: { type: "crypto" as const, code: "WELL", name: "Moonwell" },
  WIF: { type: "crypto" as const, code: "WIF", name: "Dogwifhat" },
  WLD: { type: "crypto" as const, code: "WLD", name: "Worldcoin" },
  WLUNA: {
    type: "crypto" as const,
    code: "WLUNA",
    name: "Wrapped LUNA (Legacy)",
  },
  XCN: { type: "crypto" as const, code: "XCN", name: "Onyxcoin" },
  XLM: { type: "crypto" as const, code: "XLM", name: "Stellar" },

  XTZ: { type: "crypto" as const, code: "XTZ", name: "Tezos" },
  XYO: { type: "crypto" as const, code: "XYO", name: "XYO" },
  YFI: { type: "crypto" as const, code: "YFI", name: "yearn.finance" },
  YFII: { type: "crypto" as const, code: "YFII", name: "DFI.Money" },
  ZEC: { type: "crypto" as const, code: "ZEC", name: "Zcash" },
  ZEN: { type: "crypto" as const, code: "ZEN", name: "Horizen" },
  ZETA: { type: "crypto" as const, code: "ZETA", name: "ZetaMarkets" },
  ZETACHAIN: { type: "crypto" as const, code: "ZETACHAIN", name: "ZetaChain" },
  ZK: { type: "crypto" as const, code: "ZK", name: "Polyhedra Network (ZK)" },
  ZORA: { type: "crypto" as const, code: "ZORA", name: "Zora" },
  ZRO: { type: "crypto" as const, code: "ZRO", name: "LayerZero" },
  ZRX: { type: "crypto" as const, code: "ZRX", name: "0x Protocol" },
};

const TEST_CRYPTOS = {
  // 常用幣種
  BTC: { type: "crypto" as const, code: "BTC", name: "Bitcoin" },
  ETH: { type: "crypto" as const, code: "ETH", name: "Ethereum" },
  USDT: { type: "crypto" as const, code: "USDT", name: "Tether" },
  USDC: { type: "crypto" as const, code: "USDC", name: "USD Coin" },
  XRP: { type: "crypto" as const, code: "XRP", name: "XRP" },
  ADA: { type: "crypto" as const, code: "ADA", name: "Cardano" },

  // 一般幣種，依字母排序
  "1INCH": { type: "crypto" as const, code: "1INCH", name: "1inch Network" },
  A8: { type: "crypto" as const, code: "A8", name: "Ancient8" },
  AAVE: { type: "crypto" as const, code: "AAVE", name: "Aave" },
  ABT: { type: "crypto" as const, code: "ABT", name: "Arcblock" },
  ACH: { type: "crypto" as const, code: "ACH", name: "Alchemy Pay" },
  ACS: { type: "crypto" as const, code: "ACS", name: "Access" },
  ACX: { type: "crypto" as const, code: "ACX", name: "Across Protocol" },
};

const data = process.env.NODE_ENV === "test" ? TEST_CRYPTOS : CRYPTOS;

export { data as CRYPTOS };
