const FIATS = {
  // 常用幣種
  EUR: {
    code: "EUR",
    symbol: "€",
    name: "Euro",
    country: "European Union",
    country_codes: ["EU", "EUR"],
  },
  GBP: {
    code: "GBP",
    symbol: "£",
    name: "British pound",
    country: "United Kingdom",
    country_codes: ["GB", "GBR"],
  },
  USD: {
    code: "USD",
    symbol: "$",
    name: "United States dollar",
    country: "United States of America",
    country_codes: ["US", "USA"],
  },
  INR: {
    code: "INR",
    symbol: "₹",
    name: "Indian rupee",
    country: "India",
    country_codes: ["IN", "IND"],
  },
  CAD: {
    code: "CAD",
    symbol: "C$",
    name: "Canadian dollar",
    country: "Canada",
    country_codes: ["CA", "CAN"],
  },
  AUD: {
    code: "AUD",
    symbol: "A$",
    name: "Australian dollar",
    country: "Australia",
    country_codes: ["AU", "AUS"],
  },
  CHF: {
    code: "CHF",
    symbol: "SFr.",
    name: "Swiss franc",
    country: "Switzerland",
    country_codes: ["CH", "CHE"],
  },
  MXN: {
    code: "MXN",
    symbol: "Mex$",
    name: "Mexican peso",
    country: "Mexico",
    country_codes: ["MX", "MEX"],
  },

  // 一般幣種，依字母排序
  AED: {
    code: "AED",
    symbol: "د.إ",
    name: "United Arab Emirates dirham",
    country: "United Arab Emirates",
    country_codes: ["AE", "ARE"],
  },
  AFN: {
    code: "AFN",
    symbol: "؋",
    name: "Afghanistan afghani",
    country: "Afghanistan",
    country_codes: ["AF", "AFG"],
  },
  ALL: {
    code: "ALL",
    symbol: "Lek",
    name: "Albanian lek",
    country: "Albania",
    country_codes: ["AL", "ALB"],
  },
  AMD: {
    code: "AMD",
    symbol: "֏",
    name: "Armenian dram",
    country: "Armenia",
    country_codes: ["AM", "ARM"],
  },
  ANG: {
    code: "ANG",
    symbol: "ƒ",
    name: "Netherlands Antillean guilder",
    country: "Curaçao and Sint Maarten",
    country_codes: ["CW", "CUW"], // Curaçao uses ANG, also Sint Maarten (SX)
  },
  AOA: {
    code: "AOA",
    symbol: "Kz",
    name: "Angolan kwanza",
    country: "Angola",
    country_codes: ["AO", "AGO"],
  },
  ARS: {
    code: "ARS",
    symbol: "$",
    name: "Argentine peso",
    country: "Argentina",
    country_codes: ["AR", "ARG"],
  },

  AWG: {
    code: "AWG",
    symbol: "AWG",
    name: "Aruban florin",
    country: "Aruba",
    country_codes: ["AW", "ABW"],
  },
  AZN: {
    code: "AZN",
    symbol: "man.",
    name: "Azerbaijani manat",
    country: "Azerbaijan",
    country_codes: ["AZ", "AZE"],
  },
  BAM: {
    code: "BAM",
    symbol: "KM",
    name: "Bosnia and Herzegovina convertible mark",
    country: "Bosnia and Herzegovina",
    country_codes: ["BA", "BIH"],
  },
  BBD: {
    code: "BBD",
    symbol: "BBD",
    name: "Barbadian dollar",
    country: "Barbados",
    country_codes: ["BB", "BRB"],
  },
  BDT: {
    code: "BDT",
    symbol: "Tk",
    name: "Bangladeshi taka",
    country: "Bangladesh",
    country_codes: ["BD", "BGD"],
  },
  BGN: {
    code: "BGN",
    symbol: "лв",
    name: "Bulgarian lev",
    country: "Bulgaria",
    country_codes: ["BG", "BGR"],
  },
  BHD: {
    code: "BHD",
    symbol: "BHD",
    name: "Bahraini dinar",
    country: "Bahrain",
    country_codes: ["BH", "BHR"],
  },
  BIF: {
    code: "BIF",
    symbol: "BIF",
    name: "Burundian franc",
    country: "Burundi",
    country_codes: ["BI", "BDI"],
  },
  BMD: {
    code: "BMD",
    symbol: "BMD",
    name: "Bermudian dollar",
    country: "Bermuda",
    country_codes: ["BM", "BMU"],
  },
  BND: {
    code: "BND",
    symbol: "BND",
    name: "Brunei dollar",
    country: "Brunei Darussalam",
    country_codes: ["BN", "BRN"],
  },
  BOB: {
    code: "BOB",
    symbol: "BOB",
    name: "Bolivian boliviano",
    country: "Bolivia (Plurinational State of)",
    country_codes: ["BO", "BOL"],
  },
  BRL: {
    code: "BRL",
    symbol: "R$",
    name: "Brazilian real",
    country: "Brazil",
    country_codes: ["BR", "BRA"],
  },
  BSD: {
    code: "BSD",
    symbol: "BSD",
    name: "Bahamian dollar",
    country: "Bahamas",
    country_codes: ["BS", "BHS"],
  },
  BTN: {
    code: "BTN",
    symbol: "BTN",
    name: "Bhutanese ngultrum",
    country: "Bhutan",
    country_codes: ["BT", "BTN"],
  },
  BWP: {
    code: "BWP",
    symbol: "BWP",
    name: "Botswana pula",
    country: "Botswana",
    country_codes: ["BW", "BWA"],
  },
  BYN: {
    code: "BYN",
    symbol: "BYN",
    name: "Belarusian ruble",
    country: "Belarus",
    country_codes: ["BY", "BLR"],
  },
  BZD: {
    code: "BZD",
    symbol: "BZ$",
    name: "Belizean dollar",
    country: "Belize",
    country_codes: ["BZ", "BLZ"],
  },

  CDF: {
    code: "CDF",
    symbol: "CDF",
    name: "Congolese franc",
    country: "Democratic Republic of the Congo",
    country_codes: ["CD", "COD"],
  },

  CLP: {
    code: "CLP",
    symbol: "$",
    name: "Chilean peso",
    country: "Chile",
    country_codes: ["CL", "CHL"],
  },
  CNH: {
    code: "CNH",
    symbol: "¥",
    name: "Chinese yuan (offshore)",
    country: "China",
    country_codes: ["CN", "CHN"],
  },
  CNY: {
    code: "CNY",
    symbol: "¥",
    name: "Chinese yuan",
    country: "China",
    country_codes: ["CN", "CHN"],
  },
  COP: {
    code: "COP",
    symbol: "$",
    name: "Colombian peso",
    country: "Colombia",
    country_codes: ["CO", "COL"],
  },
  CRC: {
    code: "CRC",
    symbol: "₡",
    name: "Costa Rican colón",
    country: "Costa Rica",
    country_codes: ["CR", "CRI"],
  },
  CUC: {
    code: "CUC",
    symbol: "CUC$",
    name: "Cuban Convertible peso",
    country: "Cuba",
    country_codes: ["CU", "CUB"],
  },
  CUP: {
    code: "CUP",
    symbol: "CUP",
    name: "Cuban peso",
    country: "Cuba",
    country_codes: ["CU", "CUB"],
  },
  CVE: {
    code: "CVE",
    symbol: "CVE",
    name: "Cape Verdean escudo",
    country: "Cape Verde",
    country_codes: ["CV", "CPV"],
  },
  CZK: {
    code: "CZK",
    symbol: "Kč",
    name: "Czech koruna",
    country: "Czech Republic",
    country_codes: ["CZ", "CZE"],
  },
  DJF: {
    code: "DJF",
    symbol: "DJF",
    name: "Djiboutian franc",
    country: "Djibouti",
    country_codes: ["DJ", "DJI"],
  },
  DKK: {
    code: "DKK",
    symbol: "kr",
    name: "Danish krone",
    country: "Denmark",
    country_codes: ["DK", "DNK"],
  },
  DOP: {
    code: "DOP",
    symbol: "$",
    name: "Dominican peso",
    country: "Dominican Republic",
    country_codes: ["DO", "DOM"],
  },
  DZD: {
    code: "DZD",
    symbol: "DZD",
    name: "Algerian dinar",
    country: "Algeria",
    country_codes: ["DZ", "DZA"],
  },

  EGP: {
    code: "EGP",
    symbol: "E£",
    name: "Egyptian pound",
    country: "Egypt",
    country_codes: ["EG", "EGY"],
  },
  ERN: {
    code: "ERN",
    symbol: "ERN",
    name: "Eritrean nakfa",
    country: "Eritrea",
    country_codes: ["ER", "ERI"],
  },
  ETB: {
    code: "ETB",
    symbol: "Br",
    name: "Ethiopian birr",
    country: "Ethiopia",
    country_codes: ["ET", "ETH"],
  },

  FJD: {
    code: "FJD",
    symbol: "FJD",
    name: "Fijian dollar",
    country: "Fiji",
    country_codes: ["FJ", "FJI"],
  },
  FKP: {
    code: "FKP",
    symbol: "£",
    name: "Falkland Islands pound",
    country: "Falkland Islands (Malvinas)",
    country_codes: ["FK", "FLK"],
  },

  GEL: {
    code: "GEL",
    symbol: "GEL",
    name: "Georgian lari",
    country: "Georgia",
    country_codes: ["GE", "GEO"],
  },
  GGP: {
    code: "GGP",
    symbol: "£",
    name: "Guernsey pound",
    country: "Guernsey",
    country_codes: ["GG", "GGY"],
  },
  GHS: {
    code: "GHS",
    symbol: "GH¢",
    name: "Ghanaian cedi",
    country: "Ghana",
    country_codes: ["GH", "GHA"],
  },
  GIP: {
    code: "GIP",
    symbol: "£",
    name: "Gibraltar pound",
    country: "Gibraltar",
    country_codes: ["GI", "GIB"],
  },
  GMD: {
    code: "GMD",
    symbol: "GMD",
    name: "Gambian dalasi",
    country: "Gambia",
    country_codes: ["GM", "GMB"],
  },
  GNF: {
    code: "GNF",
    symbol: "GNF",
    name: "Guinean franc",
    country: "Guinea",
    country_codes: ["GN", "GIN"],
  },
  GTQ: {
    code: "GTQ",
    symbol: "Q",
    name: "Guatemalan quetzal",
    country: "Guatemala",
    country_codes: ["GT", "GTM"],
  },
  GYD: {
    code: "GYD",
    symbol: "GYD",
    name: "Guyanese dollar",
    country: "Guyana",
    country_codes: ["GY", "GUY"],
  },

  HKD: {
    code: "HKD",
    symbol: "$",
    name: "Hong Kong dollar",
    country: "Hong Kong",
    country_codes: ["HK", "HKG"],
  },
  HNL: {
    code: "HNL",
    symbol: "L",
    name: "Honduran lempira",
    country: "Honduras",
    country_codes: ["HN", "HND"],
  },
  HTG: {
    code: "HTG",
    symbol: "HTG",
    name: "Haitian gourde",
    country: "Haiti",
    country_codes: ["HT", "HTI"],
  },
  HUF: {
    code: "HUF",
    symbol: "Ft",
    name: "Hungarian forint",
    country: "Hungary",
    country_codes: ["HU", "HUN"],
  },
  IDR: {
    code: "IDR",
    symbol: "Rp",
    name: "Indonesian rupiah",
    country: "Indonesia",
    country_codes: ["ID", "IDN"],
  },
  ILS: {
    code: "ILS",
    symbol: "₪",
    name: "Israeli shekel",
    country: "Israel",
    country_codes: ["IL", "ISR"],
  },
  IMP: {
    code: "IMP",
    symbol: "£",
    name: "Isle of Man pound",
    country: "Isle of Man",
    country_codes: ["IM", "IMN"],
  },

  IQD: {
    code: "IQD",
    symbol: "IQD",
    name: "Iraqi dinar",
    country: "Iraq",
    country_codes: ["IQ", "IRQ"],
  },
  IRR: {
    code: "IRR",
    symbol: "﷼",
    name: "Iranian rial",
    country: "Iran (Islamic Republic of)",
    country_codes: ["IR", "IRN"],
  },
  ISK: {
    code: "ISK",
    symbol: "kr",
    name: "Icelandic króna",
    country: "Iceland",
    country_codes: ["IS", "ISL"],
  },
  JEP: {
    code: "JEP",
    symbol: "£",
    name: "Jersey pound",
    country: "Jersey",
    country_codes: ["JE", "JEY"],
  },
  JMD: {
    code: "JMD",
    symbol: "J$",
    name: "Jamaican dollar",
    country: "Jamaica",
    country_codes: ["JM", "JAM"],
  },
  JOD: {
    code: "JOD",
    symbol: "JD",
    name: "Jordanian dinar",
    country: "Jordan",
    country_codes: ["JO", "JOR"],
  },
  JPY: {
    code: "JPY",
    symbol: "¥",
    name: "Japanese yen",
    country: "Japan",
    country_codes: ["JP", "JPN"],
  },

  KES: {
    code: "KES",
    symbol: "Ksh",
    name: "Kenyan shilling",
    country: "Kenya",
    country_codes: ["KE", "KEN"],
  },
  KGS: {
    code: "KGS",
    symbol: "KGS",
    name: "Kyrgyzstani som",
    country: "Kyrgyzstan",
    country_codes: ["KG", "KGZ"],
  },
  KHR: {
    code: "KHR",
    symbol: "៛",
    name: "Cambodian riel",
    country: "Cambodia",
    country_codes: ["KH", "KHM"],
  },
  KMF: {
    code: "KMF",
    symbol: "KMF",
    name: "Comorian franc",
    country: "Comoros",
    country_codes: ["KM", "COM"],
  },
  KPW: {
    code: "KPW",
    symbol: "KPW",
    name: "North Korean won",
    country: "Korea (Democratic People's Republic of)",
    country_codes: ["KP", "PRK"],
  },
  KRW: {
    code: "KRW",
    symbol: "₩",
    name: "South Korean won",
    country: "Korea (Republic of)",
    country_codes: ["KR", "KOR"],
  },
  KWD: {
    code: "KWD",
    symbol: "ك",
    name: "Kuwaiti dinar",
    country: "Kuwait",
    country_codes: ["KW", "KWT"],
  },
  KYD: {
    code: "KYD",
    symbol: "$",
    name: "Cayman Islands dollar",
    country: "Cayman Islands",
    country_codes: ["KY", "CYM"],
  },
  KZT: {
    code: "KZT",
    symbol: "₸",
    name: "Kazakhstani tenge",
    country: "Kazakhstan",
    country_codes: ["KZ", "KAZ"],
  },
  LAK: {
    code: "LAK",
    symbol: "LAK",
    name: "Lao kip",
    country: "Lao People's Democratic Republic",
    country_codes: ["LA", "LAO"],
  },
  LBP: {
    code: "LBP",
    symbol: "LBP",
    name: "Lebanese pound",
    country: "Lebanon",
    country_codes: ["LB", "LBN"],
  },
  LKR: {
    code: "LKR",
    symbol: "Rs",
    name: "Sri Lankan rupee",
    country: "Sri Lanka",
    country_codes: ["LK", "LKA"],
  },
  LRD: {
    code: "LRD",
    symbol: "L$",
    name: "Liberian dollar",
    country: "Liberia",
    country_codes: ["LR", "LBR"],
  },
  LSL: {
    code: "LSL",
    symbol: "LSL",
    name: "Lesotho loti",
    country: "Lesotho",
    country_codes: ["LS", "LSO"],
  },
  LYD: {
    code: "LYD",
    symbol: "LYD",
    name: "Libyan dinar",
    country: "Libya",
    country_codes: ["LY", "LBY"],
  },

  MAD: {
    code: "MAD",
    symbol: "د.م.",
    name: "Moroccan dirham",
    country: "Morocco",
    country_codes: ["MA", "MAR"],
  },
  MDL: {
    code: "MDL",
    symbol: "MDL",
    name: "Moldovan leu",
    country: "Moldova (Republic of)",
    country_codes: ["MD", "MDA"],
  },
  MGA: {
    code: "MGA",
    symbol: "MGA",
    name: "Malagasy ariary",
    country: "Madagascar",
    country_codes: ["MG", "MDG"],
  },
  MKD: {
    code: "MKD",
    symbol: "ден",
    name: "Macedonian denar",
    country: "North Macedonia",
    country_codes: ["MK", "MKD"],
  },
  MMK: {
    code: "MMK",
    symbol: "K",
    name: "Myanmar kyat",
    country: "Myanmar",
    country_codes: ["MM", "MMR"],
  },
  MNT: {
    code: "MNT",
    symbol: "MNT",
    name: "Mongolian tugrik",
    country: "Mongolia",
    country_codes: ["MN", "MNG"],
  },
  MOP: {
    code: "MOP",
    symbol: "MOP",
    name: "Macanese pataca",
    country: "Macau",
    country_codes: ["MO", "MAC"],
  },
  MRU: {
    code: "MRU",
    symbol: "UM",
    name: "Mauritanian ouguiya",
    country: "Mauritania",
    country_codes: ["MR", "MRT"],
  },
  MUR: {
    code: "MUR",
    symbol: "₨",
    name: "Mauritian rupee",
    country: "Mauritius",
    country_codes: ["MU", "MUS"],
  },
  MVR: {
    code: "MVR",
    symbol: "MVR",
    name: "Maldivian rufiyaa",
    country: "Maldives",
    country_codes: ["MV", "MDV"],
  },
  MWK: {
    code: "MWK",
    symbol: "MWK",
    name: "Malawian kwacha",
    country: "Malawi",
    country_codes: ["MW", "MWI"],
  },

  MYR: {
    code: "MYR",
    symbol: "RM",
    name: "Malaysian ringgit",
    country: "Malaysia",
    country_codes: ["MY", "MYS"],
  },
  MZN: {
    code: "MZN",
    symbol: "MT",
    name: "Mozambican metical",
    country: "Mozambique",
    country_codes: ["MZ", "MOZ"],
  },
  NAD: {
    code: "NAD",
    symbol: "$",
    name: "Namibian dollar",
    country: "Namibia",
    country_codes: ["NA", "NAM"],
  },
  NGN: {
    code: "NGN",
    symbol: "₦",
    name: "Nigerian naira",
    country: "Nigeria",
    country_codes: ["NG", "NGA"],
  },
  NIO: {
    code: "NIO",
    symbol: "NIO",
    name: "Nicaraguan córdoba",
    country: "Nicaragua",
    country_codes: ["NI", "NIC"],
  },
  NOK: {
    code: "NOK",
    symbol: "kr",
    name: "Norwegian krone",
    country: "Norway",
    country_codes: ["NO", "NOR"],
  },
  NPR: {
    code: "NPR",
    symbol: "₨",
    name: "Nepalese rupee",
    country: "Nepal",
    country_codes: ["NP", "NPL"],
  },
  NZD: {
    code: "NZD",
    symbol: "$",
    name: "New Zealand dollar",
    country: "New Zealand",
    country_codes: ["NZ", "NZL"],
  },

  OMR: {
    code: "OMR",
    symbol: "OMR",
    name: "Omani rial",
    country: "Oman",
    country_codes: ["OM", "OMN"],
  },
  PAB: {
    code: "PAB",
    symbol: "B/.",
    name: "Panamanian balboa",
    country: "Panama",
    country_codes: ["PA", "PAN"],
  },
  PEN: {
    code: "PEN",
    symbol: "S/.",
    name: "Peruvian sol",
    country: "Peru",
    country_codes: ["PE", "PER"],
  },
  PGK: {
    code: "PGK",
    symbol: "PGK",
    name: "Papua New Guinean kina",
    country: "Papua New Guinea",
    country_codes: ["PG", "PNG"],
  },
  PHP: {
    code: "PHP",
    symbol: "₱",
    name: "Philippine peso",
    country: "Philippines",
    country_codes: ["PH", "PHL"],
  },
  PKR: {
    code: "PKR",
    symbol: "₨",
    name: "Pakistani rupee",
    country: "Pakistan",
    country_codes: ["PK", "PAK"],
  },
  PLN: {
    code: "PLN",
    symbol: "zł",
    name: "Polish złoty",
    country: "Poland",
    country_codes: ["PL", "POL"],
  },
  PYG: {
    code: "PYG",
    symbol: "₲",
    name: "Paraguayan guaraní",
    country: "Paraguay",
    country_codes: ["PY", "PRY"],
  },
  QAR: {
    code: "QAR",
    symbol: "QR",
    name: "Qatari riyal",
    country: "Qatar",
    country_codes: ["QA", "QAT"],
  },
  RON: {
    code: "RON",
    symbol: "L",
    name: "Romanian leu",
    country: "Romania",
    country_codes: ["RO", "ROU"],
  },
  RSD: {
    code: "RSD",
    symbol: "РСД",
    name: "Serbian dinar",
    country: "Serbia",
    country_codes: ["RS", "SRB"],
  },
  RUB: {
    code: "RUB",
    symbol: "руб",
    name: "Russian rouble",
    country: "Russia",
    country_codes: ["RU", "RUS"],
  },
  RWF: {
    code: "RWF",
    symbol: "RWF",
    name: "Rwandan franc",
    country: "Rwanda",
    country_codes: ["RW", "RWA"],
  },

  SAR: {
    code: "SAR",
    symbol: "SR",
    name: "Saudi riyal",
    country: "Saudi Arabia",
    country_codes: ["SA", "SAU"],
  },
  SBD: {
    code: "SBD",
    symbol: "SI$",
    name: "Solomon Islands dollar",
    country: "Solomon Islands",
    country_codes: ["SB", "SLB"],
  },
  SCR: {
    code: "SCR",
    symbol: "₨",
    name: "Seychellois rupee",
    country: "Seychelles",
    country_codes: ["SC", "SYC"],
  },
  SDG: {
    code: "SDG",
    symbol: "SDG",
    name: "Sudanese pound",
    country: "Sudan",
    country_codes: ["SD", "SDN"],
  },
  SEK: {
    code: "SEK",
    symbol: "kr",
    name: "Swedish krona",
    country: "Sweden",
    country_codes: ["SE", "SWE"],
  },
  SGD: {
    code: "SGD",
    symbol: "S$",
    name: "Singapore dollar",
    country: "Singapore",
    country_codes: ["SG", "SGP"],
  },
  SHP: {
    code: "SHP",
    symbol: "£",
    name: "Saint Helena pound",
    country: "Saint Helena, Ascension and Tristan da Cunha",
    country_codes: ["SH", "SHN"],
  },
  SLL: {
    code: "SLL",
    symbol: "SLL",
    name: "Sierra Leonean leone",
    country: "Sierra Leone",
    country_codes: ["SL", "SLE"],
  },
  SLE: {
    code: "SLE",
    symbol: "SLE",
    name: "Sierra Leonean leone",
    country: "Sierra Leone",
    country_codes: ["SL", "SLE"],
  },
  SOS: {
    code: "SOS",
    symbol: "Sh.So.",
    name: "Somali shilling",
    country: "Somalia",
    country_codes: ["SO", "SOM"],
  },
  SRD: {
    code: "SRD",
    symbol: "$",
    name: "Surinamese dollar",
    country: "Suriname",
    country_codes: ["SR", "SUR"],
  },
  SSP: {
    code: "SSP",
    symbol: "SSP",
    name: "South Sudanese pound",
    country: "South Sudan",
    country_codes: ["SS", "SSD"],
  },
  STD: {
    code: "STD",
    symbol: "STD",
    name: "São Tomé & Príncipe dobra",
    country: "Sao Tome and Principe",
    country_codes: ["ST", "STP"],
  },
  STN: {
    code: "STN",
    symbol: "STN",
    name: "São Tomé & Príncipe dobra",
    country: "Sao Tome and Principe",
    country_codes: ["ST", "STP"],
  },
  SVC: {
    code: "SVC",
    symbol: "₡",
    name: "Salvadoran colón",
    country: "El Salvador",
    country_codes: ["SV", "SLV"],
  },
  SYP: {
    code: "SYP",
    symbol: "£",
    name: "Syrian pound",
    country: "Syrian Arab Republic",
    country_codes: ["SY", "SYR"],
  },
  SZL: {
    code: "SZL",
    symbol: "SZL",
    name: "Swazi lilangeni",
    country: "Eswatini",
    country_codes: ["SZ", "SWZ"],
  },
  THB: {
    code: "THB",
    symbol: "฿",
    name: "Thai baht",
    country: "Thailand",
    country_codes: ["TH", "THA"],
  },
  TJS: {
    code: "TJS",
    symbol: "TJS",
    name: "Tajikistani somoni",
    country: "Tajikistan",
    country_codes: ["TJ", "TJK"],
  },
  TMT: {
    code: "TMT",
    symbol: "TMT",
    name: "Turkmenistani manat",
    country: "Turkmenistan",
    country_codes: ["TM", "TKM"],
  },
  TND: {
    code: "TND",
    symbol: "TND",
    name: "Tunisian dinar",
    country: "Tunisia",
    country_codes: ["TN", "TUN"],
  },
  TOP: {
    code: "TOP",
    symbol: "TOP",
    name: "Tongan pa'anga",
    country: "Tonga",
    country_codes: ["TO", "TON"],
  },
  TRY: {
    code: "TRY",
    symbol: "TL",
    name: "Turkish lira",
    country: "Turkey",
    country_codes: ["TR", "TUR"],
  },
  TTD: {
    code: "TTD",
    symbol: "TTD",
    name: "Trinidad and Tobago dollar",
    country: "Trinidad and Tobago",
    country_codes: ["TT", "TTO"],
  },
  TWD: {
    code: "TWD",
    symbol: "NT$",
    name: "Taiwanese New Taiwan dollar",
    country: "Taiwan",
    country_codes: ["TW", "TWN"],
  },
  TZS: {
    code: "TZS",
    symbol: "tzs",
    name: "Tanzanian shilling",
    country: "Tanzania, United Republic of",
    country_codes: ["TZ", "TZA"],
  },

  UAH: {
    code: "UAH",
    symbol: "₴",
    name: "Ukrainian hryvnia",
    country: "Ukraine",
    country_codes: ["UA", "UKR"],
  },
  UGX: {
    code: "UGX",
    symbol: "Ush",
    name: "Ugandan shilling",
    country: "Uganda",
    country_codes: ["UG", "UGA"],
  },

  UYU: {
    code: "UYU",
    symbol: "$U",
    name: "Uruguayan peso",
    country: "Uruguay",
    country_codes: ["UY", "URY"],
  },
  UYW: {
    code: "UYW",
    symbol: "UYW",
    name: "Unidad Previsional",
    country: "Uruguay",
    country_codes: ["UY", "URY"],
  },
  UZS: {
    code: "UZS",
    symbol: "UZS",
    name: "Uzbekistani som",
    country: "Uzbekistan",
    country_codes: ["UZ", "UZB"],
  },
  VES: {
    code: "VES",
    symbol: "Bs.",
    name: "Venezuelan bolívar soberano",
    country: "Venezuela (Bolivarian Republic of)",
    country_codes: ["VE", "VEN"],
  },
  VND: {
    code: "VND",
    symbol: "VND",
    name: "Vietnamese dong",
    country: "Viet Nam",
    country_codes: ["VN", "VNM"],
  },
  VUV: {
    code: "VUV",
    symbol: "VUV",
    name: "Vanuatu vatu",
    country: "Vanuatu",
    country_codes: ["VU", "VUT"],
  },
  WST: {
    code: "WST",
    symbol: "WST",
    name: "Samoan tala",
    country: "Samoa",
    country_codes: ["WS", "WSM"],
  },
  XAF: {
    code: "XAF",
    symbol: "XAF",
    name: "Central African CFA franc",
    country: "Central African States",
    country_codes: ["CF", "CAF"], // Used by multiple countries in CEMAC region
  },
  XCD: {
    code: "XCD",
    symbol: "$",
    name: "East Caribbean dollar",
    country: "East Caribbean States",
    country_codes: ["AG", "ATG"], // Includes multiple OECS members, example Antigua and Barbuda
  },
  XCG: {
    code: "XCG",
    symbol: "Cg",
    name: "Caribbean Guilder",
    country: "Caribbean Netherlands",
    country_codes: ["BQ", "BES"],
  },
  XOF: {
    code: "XOF",
    symbol: "XOF",
    name: "West African CFA franc",
    country: "West African States",
    country_codes: ["SN", "SEN"], // Used by multiple countries in UEMOA
  },
  XPF: {
    code: "XPF",
    symbol: "XPF",
    name: "CFP franc",
    country: "French Polynesia, New Caledonia, Wallis and Futuna",
    country_codes: ["PF", "PYF"], // French Polynesia as example
  },
  YER: {
    code: "YER",
    symbol: "﷼",
    name: "Yemeni rial",
    country: "Yemen",
    country_codes: ["YE", "YEM"],
  },
  ZAR: {
    code: "ZAR",
    symbol: "R",
    name: "South African rand",
    country: "South Africa",
    country_codes: ["ZA", "ZAF"],
  },
  ZMW: {
    code: "ZMW",
    symbol: "ZMW",
    name: "Zambian kwacha",
    country: "Zambia",
    country_codes: ["ZM", "ZMB"],
  },
  ZWG: {
    code: "ZWG",
    symbol: "ZWG",
    name: "Zimbabwe Gold",
    country: "Zimbabwe",
    country_codes: ["ZW", "ZWE"],
  },
};

const TEST_FIATS = {
  // 常用幣種
  EUR: {
    code: "EUR",
    symbol: "€",
    name: "Euro",
    country: "European Union",
    country_codes: ["EU", "EUR"],
  },
  GBP: {
    code: "GBP",
    symbol: "£",
    name: "British pound",
    country: "United Kingdom",
    country_codes: ["GB", "GBR"],
  },
  USD: {
    code: "USD",
    symbol: "$",
    name: "United States dollar",
    country: "United States of America",
    country_codes: ["US", "USA"],
  },
  INR: {
    code: "INR",
    symbol: "₹",
    name: "Indian rupee",
    country: "India",
    country_codes: ["IN", "IND"],
  },
  CAD: {
    code: "CAD",
    symbol: "C$",
    name: "Canadian dollar",
    country: "Canada",
    country_codes: ["CA", "CAN"],
  },
  AUD: {
    code: "AUD",
    symbol: "A$",
    name: "Australian dollar",
    country: "Australia",
    country_codes: ["AU", "AUS"],
  },
  CHF: {
    code: "CHF",
    symbol: "SFr.",
    name: "Swiss franc",
    country: "Switzerland",
    country_codes: ["CH", "CHE"],
  },
  MXN: {
    code: "MXN",
    symbol: "Mex$",
    name: "Mexican peso",
    country: "Mexico",
    country_codes: ["MX", "MEX"],
  },

  // 一般幣種，依字母排序
  AED: {
    code: "AED",
    symbol: "د.إ",
    name: "United Arab Emirates dirham",
    country: "United Arab Emirates",
    country_codes: ["AE", "ARE"],
  },
  AFN: {
    code: "AFN",
    symbol: "؋",
    name: "Afghanistan afghani",
    country: "Afghanistan",
    country_codes: ["AF", "AFG"],
  },
  ALL: {
    code: "ALL",
    symbol: "Lek",
    name: "Albanian lek",
    country: "Albania",
    country_codes: ["AL", "ALB"],
  },
  AMD: {
    code: "AMD",
    symbol: "֏",
    name: "Armenian dram",
    country: "Armenia",
    country_codes: ["AM", "ARM"],
  },
  ANG: {
    code: "ANG",
    symbol: "ƒ",
    name: "Netherlands Antillean guilder",
    country: "Curaçao and Sint Maarten",
    country_codes: ["CW", "CUW"], // Curaçao uses ANG, also Sint Maarten (SX)
  },
  AOA: {
    code: "AOA",
    symbol: "Kz",
    name: "Angolan kwanza",
    country: "Angola",
    country_codes: ["AO", "AGO"],
  },
  ARS: {
    code: "ARS",
    symbol: "$",
    name: "Argentine peso",
    country: "Argentina",
    country_codes: ["AR", "ARG"],
  },

  AWG: {
    code: "AWG",
    symbol: "AWG",
    name: "Aruban florin",
    country: "Aruba",
    country_codes: ["AW", "ABW"],
  },
  AZN: {
    code: "AZN",
    symbol: "man.",
    name: "Azerbaijani manat",
    country: "Azerbaijan",
    country_codes: ["AZ", "AZE"],
  },
};

const data = process.env.NODE_ENV == "test" ? TEST_FIATS : FIATS;

export { data as FIATS };
