/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as ConverterIndexRouteImport } from "./routes/converter/index";

const ConverterIndexRoute = ConverterIndexRouteImport.update({
  id: "/converter/",
  path: "/converter/",
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  "/converter": typeof ConverterIndexRoute;
}
export interface FileRoutesByTo {
  "/converter": typeof ConverterIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/converter/": typeof ConverterIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: "/converter";
  fileRoutesByTo: FileRoutesByTo;
  to: "/converter";
  id: "__root__" | "/converter/";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  ConverterIndexRoute: typeof ConverterIndexRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/converter/": {
      id: "/converter/";
      path: "/converter";
      fullPath: "/converter";
      preLoaderRoute: typeof ConverterIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren: RootRouteChildren = {
  ConverterIndexRoute: ConverterIndexRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
