/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as ConverterIndexRouteImport } from "./routes/converter/index";
import { Route as TrendsChar123VisualChar125RouteImport } from "./routes/trends/{-$visual}";

const ConverterIndexRoute = ConverterIndexRouteImport.update({
  id: "/converter/",
  path: "/converter/",
  getParentRoute: () => rootRouteImport,
} as any);
const TrendsChar123VisualChar125Route =
  TrendsChar123VisualChar125RouteImport.update({
    id: "/trends/{-$visual}",
    path: "/trends/{-$visual}",
    getParentRoute: () => rootRouteImport,
  } as any);

export interface FileRoutesByFullPath {
  "/trends/{-$visual}": typeof TrendsChar123VisualChar125Route;
  "/converter": typeof ConverterIndexRoute;
}
export interface FileRoutesByTo {
  "/trends/{-$visual}": typeof TrendsChar123VisualChar125Route;
  "/converter": typeof ConverterIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/trends/{-$visual}": typeof TrendsChar123VisualChar125Route;
  "/converter/": typeof ConverterIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: "/trends/{-$visual}" | "/converter";
  fileRoutesByTo: FileRoutesByTo;
  to: "/trends/{-$visual}" | "/converter";
  id: "__root__" | "/trends/{-$visual}" | "/converter/";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  TrendsChar123VisualChar125Route: typeof TrendsChar123VisualChar125Route;
  ConverterIndexRoute: typeof ConverterIndexRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/converter/": {
      id: "/converter/";
      path: "/converter";
      fullPath: "/converter";
      preLoaderRoute: typeof ConverterIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/trends/{-$visual}": {
      id: "/trends/{-$visual}";
      path: "/trends/{-$visual}";
      fullPath: "/trends/{-$visual}";
      preLoaderRoute: typeof TrendsChar123VisualChar125RouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren: RootRouteChildren = {
  TrendsChar123VisualChar125Route: TrendsChar123VisualChar125Route,
  ConverterIndexRoute: ConverterIndexRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
